version: '3.9'

services:
  appointments-project-back-qa:
    container_name: appointments-project-back-qa
    build:
      context: ../../
      dockerfile: Web_back/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5104:8080"
    networks:
      -  appointments_network
    
    labels:
      - com.appointments.environment=qa

networks:
  appointments_network:
    external: true
