version: "3.9"

services:
  # ğŸ—„ï¸ SQL Server - DEVELOP
  appointments-sqlserver-develop:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: appointments-sqlserver-develop
    restart: always
    env_file:
      - .env
    ports:
      - "1438:1433"
    volumes:
      - sqldata_develop:/var/opt/mssql
    networks:
      - appointments_network

  # ğŸ—„ï¸ SQL Server - QA
  appointments-sqlserver-qa:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: appointments-sqlserver-qa
    restart: always
    env_file:
      - .env
    ports:
      - "1436:1433"
    volumes:
      - sqldata_qa:/var/opt/mssql
    networks:
      - appointments_network

  # ğŸ—„ï¸ SQL Server - STAGING
  appointments-sqlserver-staging:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: appointments-sqlserver-staging
    restart: always
    env_file:
      - .env
    ports:
      - "1437:1433"
    volumes:
      - sqldata_staging:/var/opt/mssql
    networks:
      - appointments_network

  # ğŸ—„ï¸ SQL Server - PROD
  appointments-sqlserver-prod:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: appointments-sqlserver-prod
    restart: always
    env_file:
      - .env
    ports:
      - "1435:1433"
    volumes:
      - sqldata_prod:/var/opt/mssql
    networks:
      - appointments_network

volumes:
  sqldata_develop:
  sqldata_qa:
  sqldata_staging:
  sqldata_prod:

networks:
  appointments_network:
    name: appointments_network
    driver: bridge
    external: true
