version: '3.8'

services:
  appointments-project-back-staging:
    container_name: appointments-project-back-staging
    build:
      context: ../..
      dockerfile: Web_back/Dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - "5105:8080"
    networks:
      - network_staging 
    labels:
      - com.appointments.environment=staging
    command: >
      sh -c "
        echo 'ğŸ•’ Esperando a que SQL Server estÃ© listo...';
        for i in {1..30}; do
          /opt/mssql-tools/bin/sqlcmd -S appointments-sql-staging -U sa -P \"$SA_PASSWORD\" -Q 'SELECT 1' && break;
          echo 'â³ SQL aÃºn no responde, reintentando...';
          sleep 3;
        done;

        echo 'ğŸ—ï¸ Aplicando migraciones de Entity Framework...';
        dotnet ef database update --project ./Entity/Entity.csproj --startup-project ./Web_back/Web_back.csproj;

        echo 'âœ… Migraciones completadas. Iniciando la API...';
        dotnet ./Web_back/bin/Release/net8.0/Web_back.dll
      "

networks:
  network_staging:
    external: true
